const companies_list = [
  {
    name: "Google",
    logo: "https://logo.clearbit.com/google.com",
    website: "https://www.google.com",
    rating: 4.2,
    reviews: 3200,
    industry: "Technology",
    type: "IT",
  },
  {
    name: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    website: "https://www.amazon.com",
    rating: 4.0,
    reviews: 2900,
    industry: "E-commerce",
    type: "Retail",
  },
  {
    name: "Tesla",
    logo: "https://logo.clearbit.com/tesla.com",
    website: "https://www.tesla.com",
    rating: 4.5,
    reviews: 1800,
    industry: "Automotive",
    type: "Manufacturing",
  },
  {
    name: "Spotify",
    logo: "https://logo.clearbit.com/spotify.com",
    website: "https://www.spotify.com",
    rating: 4.1,
    reviews: 1500,
    industry: "Entertainment",
    type: "Media",
  },
  {
    name: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    website: "https://www.adobe.com",
    rating: 4.3,
    reviews: 2100,
    industry: "Design",
    type: "Software",
  },
  {
    name: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    website: "https://www.amazon.com",
    rating: 4.0,
    reviews: 2900,
    industry: "E-commerce",
    type: "Retail",
  },
  {
    name: "Tesla",
    logo: "https://logo.clearbit.com/tesla.com",
    website: "https://www.tesla.com",
    rating: 4.5,
    reviews: 1800,
    industry: "Automotive",
    type: "Manufacturing",
  },
  {
    name: "Spotify",
    logo: "https://logo.clearbit.com/spotify.com",
    website: "https://www.spotify.com",
    rating: 4.1,
    reviews: 1500,
    industry: "Entertainment",
    type: "Media",
  },
  {
    name: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    website: "https://www.adobe.com",
    rating: 4.3,
    reviews: 2100,
    industry: "Design",
    type: "Software",
  },
  {
    name: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    website: "https://www.amazon.com",
    rating: 4.0,
    reviews: 2900,
    industry: "E-commerce",
    type: "Retail",
  },
  {
    name: "Tesla",
    logo: "https://logo.clearbit.com/tesla.com",
    website: "https://www.tesla.com",
    rating: 4.5,
    reviews: 1800,
    industry: "Automotive",
    type: "Manufacturing",
  },
  {
    name: "Spotify",
    logo: "https://logo.clearbit.com/spotify.com",
    website: "https://www.spotify.com",
    rating: 4.1,
    reviews: 1500,
    industry: "Entertainment",
    type: "Media",
  },
  {
    name: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    website: "https://www.adobe.com",
    rating: 4.3,
    reviews: 2100,
    industry: "Design",
    type: "Software",
  },
  {
    name: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    website: "https://www.amazon.com",
    rating: 4.0,
    reviews: 2900,
    industry: "E-commerce",
    type: "Retail",
  },
  {
    name: "Tesla",
    logo: "https://logo.clearbit.com/tesla.com",
    website: "https://www.tesla.com",
    rating: 4.5,
    reviews: 1800,
    industry: "Automotive",
    type: "Manufacturing",
  },
  {
    name: "Spotify",
    logo: "https://logo.clearbit.com/spotify.com",
    website: "https://www.spotify.com",
    rating: 4.1,
    reviews: 1500,
    industry: "Entertainment",
    type: "Media",
  },
  {
    name: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    website: "https://www.adobe.com",
    rating: 4.3,
    reviews: 2100,
    industry: "Design",
    type: "Software",
  },
];

const industries = [
  "Technology",
  "E-commerce",
  "Automotive",
  "Entertainment",
  "Design",
];

const jobData = [
  {
    title: "Frontend Developer",
    company: "Tech Solutions",
    location: "Mumbai",
    type: "Full Time",
    category: "engineering",
    description: "Build modern UI with React and Tailwind CSS.",
    salary: 80000,
    datePosted: "2023-10-01",
    companySize: "SME",
    educationLevel: "Bachelor",
  },
  {
    title: "UI/UX Designer",
    company: "Creative Minds",
    location: "Delhi",
    type: "Freelance",
    category: "design",
    description: "Design intuitive interfaces for mobile apps.",
    salary: 60000,
    datePosted: "2023-09-15",
    companySize: "Startup",
    educationLevel: "Master",
  },
  {
    title: "Backend Engineer",
    company: "DataStream",
    location: "Bangalore",
    type: "Full Time",
    category: "engineering",
    description: "Develop APIs with Node.js and Express.",
    salary: 90000,
    datePosted: "2023-10-10",
    companySize: "Large Enterprise",
    educationLevel: "Bachelor",
  },
  {
    title: "Digital Marketer",
    company: "MarketWise",
    location: "Pune",
    type: "Part Time",
    category: "marketing",
    description: "Manage social media campaigns and SEO.",
    salary: 50000,
    datePosted: "2023-09-20",
    companySize: "SME",
    educationLevel: "High School",
  },
  {
    title: "Software Tester",
    company: "QA Experts",
    location: "Hyderabad",
    type: "Internship",
    category: "engineering",
    description: "Write test cases and automate QA processes.",
    salary: 40000,
    datePosted: "2023-10-05",
    companySize: "Startup",
    educationLevel: "Bachelor",
  },
  {
    title: "Data Scientist",
    company: "Analytics Corp",
    location: "Chennai",
    type: "Full Time",
    category: "engineering",
    description: "Analyze data and build machine learning models.",
    salary: 110000,
    datePosted: "2023-09-28",
    companySize: "Large Enterprise",
    educationLevel: "PhD",
  },
  {
    title: "Product Manager",
    company: "Innovate Inc",
    location: "Gurgaon",
    type: "Full Time",
    category: "management",
    description: "Lead product development and strategy.",
    salary: 120000,
    datePosted: "2023-10-03",
    companySize: "Large Enterprise",
    educationLevel: "Master",
  },
  {
    title: "DevOps Engineer",
    company: "Cloud Masters",
    location: "Bangalore",
    type: "Full Time",
    category: "engineering",
    description: "Manage CI/CD pipelines and cloud infrastructure.",
    salary: 100000,
    datePosted: "2023-09-25",
    companySize: "SME",
    educationLevel: "Bachelor",
  },
  {
    title: "Content Writer",
    company: "Media Hub",
    location: "Mumbai",
    type: "Part Time",
    category: "writing",
    description: "Create engaging content for blogs and social media.",
    salary: 45000,
    datePosted: "2023-09-18",
    companySize: "Startup",
    educationLevel: "Bachelor",
  },
  {
    title: "HR Manager",
    company: "Talent Pool",
    location: "Delhi",
    type: "Full Time",
    category: "human resources",
    description: "Oversee recruitment and employee relations.",
    salary: 70000,
    datePosted: "2023-10-08",
    companySize: "SME",
    educationLevel: "Master",
  },
  {
    title: "Financial Analyst",
    company: "Finance Gurus",
    location: "Pune",
    type: "Full Time",
    category: "finance",
    description: "Analyze financial data and prepare reports.",
    salary: 85000,
    datePosted: "2023-09-22",
    companySize: "Large Enterprise",
    educationLevel: "Bachelor",
  },
  {
    title: "Graphic Designer",
    company: "Artistic Creations",
    location: "Hyderabad",
    type: "Freelance",
    category: "design",
    description: "Create visual content for digital and print media.",
    salary: 55000,
    datePosted: "2023-09-30",
    companySize: "Startup",
    educationLevel: "Bachelor",
  },
  {
    title: "Sales Executive",
    company: "Sales Pros",
    location: "Bangalore",
    type: "Full Time",
    category: "sales",
    description: "Drive sales and build client relationships.",
    salary: 65000,
    datePosted: "2023-10-02",
    companySize: "SME",
    educationLevel: "High School",
  },
  {
    title: "Mobile App Developer",
    company: "App Innovators",
    location: "Chennai",
    type: "Full Time",
    category: "engineering",
    description: "Develop mobile applications for iOS and Android.",
    salary: 95000,
    datePosted: "2023-09-27",
    companySize: "Large Enterprise",
    educationLevel: "Bachelor",
  },
  {
    title: "Network Engineer",
    company: "Connect Solutions",
    location: "Gurgaon",
    type: "Full Time",
    category: "engineering",
    description: "Design and manage computer networks.",
    salary: 80000,
    datePosted: "2023-10-04",
    companySize: "SME",
    educationLevel: "Bachelor",
  },
  {
    title: "Marketing Specialist",
    company: "Brand Builders",
    location: "Mumbai",
    type: "Full Time",
    category: "marketing",
    description: "Develop and implement marketing strategies.",
    salary: 75000,
    datePosted: "2023-09-21",
    companySize: "Large Enterprise",
    educationLevel: "Master",
  },
  {
    title: "Customer Support Representative",
    company: "Support Central",
    location: "Delhi",
    type: "Part Time",
    category: "customer service",
    description: "Provide support and assistance to customers.",
    salary: 40000,
    datePosted: "2023-09-29",
    companySize: "Startup",
    educationLevel: "High School",
  },
  {
    title: "Project Manager",
    company: "Project Experts",
    location: "Pune",
    type: "Full Time",
    category: "management",
    description: "Plan and execute projects to meet business objectives.",
    salary: 100000,
    datePosted: "2023-10-06",
    companySize: "Large Enterprise",
    educationLevel: "Master",
  },
  {
    title: "Software Architect",
    company: "Architecture Firm",
    location: "Hyderabad",
    type: "Full Time",
    category: "engineering",
    description: "Design software systems and oversee development.",
    salary: 130000,
    datePosted: "2023-09-24",
    companySize: "SME",
    educationLevel: "PhD",
  },
  {
    title: "SEO Specialist",
    company: "SEO Masters",
    location: "Bangalore",
    type: "Full Time",
    category: "marketing",
    description: "Optimize websites for search engines.",
    salary: 60000,
    datePosted: "2023-10-01",
    companySize: "Startup",
    educationLevel: "Bachelor",
  },
  {
    title: "Business Analyst",
    company: "Business Insights",
    location: "Chennai",
    type: "Full Time",
    category: "business",
    description: "Analyze business processes and recommend improvements.",
    salary: 70000,
    datePosted: "2023-09-26",
    companySize: "Large Enterprise",
    educationLevel: "Master",
  },
  {
    title: "Technical Writer",
    company: "Docu Experts",
    location: "Gurgaon",
    type: "Freelance",
    category: "writing",
    description: "Create technical documentation and manuals.",
    salary: 50000,
    datePosted: "2023-10-07",
    companySize: "SME",
    educationLevel: "Bachelor",
  },
];

const profile_data = {
  info: {
    name: "John Doe",
    location: "Sample City, Sample State",
    dob: "Jan 10, 2025",
    email: "test@gmail.cpm",
    title: " Software Developer",
    gender: "Male",
    phone: "+91 1234567890",
  },
  education: [
    {
      title: "Graduation",
      subtitle: "B.Tech in Information Technology",
      score: "CGPA: 8.00",
    },
    {
      title: "Class 12th",
      subtitle: "ABC Junior College",
      score: "70.00%",
    },
    {
      title: "Class 10th",
      subtitle: "XYZ High School",
      score: "75.00%",
    },
  ],
  keySkills: [
    "JavaScript",
    "React Native",
    "React.js",
    "MongoDB",
    "Node.js",
    "Express.js",
    "MySQL",
    "Bootstrap",
    "Redux",
    "Software Engineering",
    "Mobile Development",
  ],
  languages: [
    {
      name: "English",
      proficiency: "Fluent",
    },
    {
      name: "Hindi",
      proficiency: "Fluent",
    },
  ],
  internships: [
    {
      company: "Tech Solutions Pvt. Ltd.",
      period: "Jan'24 to Jun'24",
    },
  ],
  projects: [
    {
      name: "E-Commerce Platform",
      period: "May'24 to May'24",
    },
    {
      name: "Portfolio Website",
      period: "Mar'24 to Mar'24",
    },
    {
      name: "Company Internal Dashboard",
      period: "Jan'24 to Feb'24",
    },
    {
      name: "Chat App",
      period: "Oct'23 to Mar'24",
    },
  ],
  profileSummary:
    "Dedicated software developer with hands-on experience in mobile and web application development. Proficient in building cross-platform apps using React Native, and developing full-stack web apps with Node.js and MongoDB.",
  certifications: [
    {
      title: "Cloud Fundamentals",
      issuer: "Online Learning Platform",
      validFrom: "Sep'23",
      expires: "Does not expire",
    },
    {
      title: "Mobile App Programming",
      issuer: "Tech Skills Institute",
      validFrom: "Dec'22",
      expires: "Does not expire",
    },
    {
      title: "Web Design Basics",
      issuer: "Tech Skills Institute",
      validFrom: "Apr'21",
      expires: "Does not expire",
    },
    {
      title: "IoT Essentials",
      issuer: "Online Learning Platform",
      validFrom: "Mar'20",
      expires: "Does not expire",
    },
  ],
  competitiveExams: [
    {
      name: "Engineering Entrance Exam",
      details: "Secured rank: 123456",
    },
  ],
  academicAchievements: [
    {
      during: "During Graduation",
      achievement: "Consistently in Top 5 of class",
    },
  ],
  resume: {
    fileName: "sample_resume.pdf",
    uploadedOn: "Jan 10, 2025",
    note: "Supported formats: doc, docx, rtf, pdf, up to 2MB",
  },
};

const links = [
  "Preference",
  "Education",
  "Key skills",
  "Languages",
  "Internships",
  "Projects",
  "Profile summary",
  "Accomplishments",
  "Competitive exams",
  "Employment",
  "Academic achievements",
];

const comapany_Info_jobData = [
  {
    title: "AI Engineer",
    location: "Maharashtra Mumbai, Pune",
    daysAgo: "24 days ago",
  },
  {
    title: "Software Developer",
    location: "Karnataka Bangalore",
    daysAgo: "10 days ago",
  },
  {
    title: "Data Scientist",
    location: "Delhi New Delhi",
    daysAgo: "5 days ago",
  },
  {
    title: "Product Manager",
    location: "Telangana Hyderabad",
    daysAgo: "15 days ago",
  },
  {
    title: "UX Designer",
    location: "Gujarat Ahmedabad",
    daysAgo: "8 days ago",
  },
  {
    title: "DevOps Engineer",
    location: "Tamil Nadu Chennai",
    daysAgo: "12 days ago",
  },
  {
    title: "Frontend Developer",
    location: "West Bengal Kolkata",
    daysAgo: "18 days ago",
  },
  {
    title: "Backend Developer",
    location: "Maharashtra Nagpur",
    daysAgo: "22 days ago",
  },
  {
    title: "QA Engineer",
    location: "Uttar Pradesh Noida",
    daysAgo: "3 days ago",
  },
  {
    title: "Systems Analyst",
    location: "Kerala Kochi",
    daysAgo: "20 days ago",
  },
];

const jobLocations = [
  { name: "Maharashtra", jobs: "130 jobs" },
  { name: "Karnataka", jobs: "120 jobs" },
  { name: "Delhi", jobs: "110 jobs" },
  { name: "Telangana", jobs: "100 jobs" },
  { name: "Gujarat", jobs: "90 jobs" },
  { name: "Tamil Nadu", jobs: "80 jobs" },
  { name: "West Bengal", jobs: "70 jobs" },
  { name: "Uttar Pradesh", jobs: "60 jobs" },
  { name: "Kerala", jobs: "50 jobs" },
  { name: "Rajasthan", jobs: "40 jobs" },
];

const reviews = [
  {
    name: "Senior Consultant",
    rating: "3.5",
    date: "24 Jun 2024",
    title: "Decent company to work for",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet iusto autem esse dolores eaque odio? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium, labore.",
  },
  {
    name: "Project Manager",
    rating: "4.0",
    date: "20 Jun 2024",
    title: "Great work environment",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet iusto autem esse dolores eaque odio? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium, labore.",
  },
  {
    name: "Software Engineer",
    rating: "4.5",
    date: "18 Jun 2024",
    title: "Innovative projects",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet iusto autem esse dolores eaque odio? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium, labore.",
  },
  {
    name: "Data Scientist",
    rating: "3.8",
    date: "15 Jun 2024",
    title: "Challenging and rewarding",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet iusto autem esse dolores eaque odio? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium, labore.",
  },
  {
    name: "UX Designer",
    rating: "4.2",
    date: "10 Jun 2024",
    title: "Creative and supportive",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet iusto autem esse dolores eaque odio? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium, labore.",
  },
  {
    name: "DevOps Engineer",
    rating: "4.7",
    date: "05 Jun 2024",
    title: "Excellent team collaboration",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet iusto autem esse dolores eaque odio? Lorem ipsum dolor sit amet, consectetur adipisicing elit. Praesentium, labore.",
  },
];

const CompanyJobsData = [
  {
    id: 1,
    title: "Software Developer",
    location: "Pune",
    company: "Microsoft",
    logo: "https://logo.clearbit.com/microsoft.com",
    type: "Full Time",
    salary: "₹6,00,000 – ₹10,00,000 LPA",
    responsibilities: [
      "Design and develop web applications using React and Node.js.",
      "Collaborate with product and design teams.",
      "Write clean, maintainable code.",
      "Conduct code reviews and troubleshoot bugs.",
    ],
    skills: ["React.js", "Node.js", "MongoDB", "REST API", "Git"],
    qualifications: [
      "B.E./B.Tech in Computer Science",
      "1–3 years of experience",
    ],
    perks: ["Remote work", "Health insurance", "Learning budget"],
  },
  {
    id: 2,
    title: "Frontend Developer",
    location: "Mumbai",
    company: "Google",
    logo: "https://logo.clearbit.com/google.com",
    type: "Full Time",
    salary: "₹8,00,000 – ₹12,00,000 LPA",
    responsibilities: [
      "Build interactive UI with React.",
      "Optimize application for speed and scalability.",
      "Ensure high code quality and maintainability.",
    ],
    skills: ["JavaScript", "HTML/CSS", "React", "Redux", "Tailwind"],
    qualifications: [
      "B.Sc./B.E. in IT/Computer Science",
      "2+ years of experience",
    ],
    perks: ["Hybrid Work", "Free Meals", "Gym Membership"],
  },
  {
    id: 3,
    title: "Backend Developer",
    location: "Bangalore",
    company: "Amazon",
    logo: "https://logo.clearbit.com/amazon.com",
    type: "Full Time",
    salary: "₹10,00,000 – ₹15,00,000 LPA",
    responsibilities: [
      "Build scalable backend APIs using Node.js and Express.",
      "Manage databases and ensure data security.",
      "Integrate third-party APIs and services.",
    ],
    skills: ["Node.js", "Express", "MongoDB", "AWS", "Docker"],
    qualifications: [
      "B.Tech in Computer Engineering",
      "2–4 years of experience",
    ],
    perks: ["Stock options", "Medical coverage", "Work-from-home flexibility"],
  },
  {
    id: 4,
    title: "UI/UX Designer",
    location: "Hyderabad",
    company: "Adobe",
    logo: "https://logo.clearbit.com/adobe.com",
    type: "Full Time",
    salary: "₹7,00,000 – ₹9,00,000 LPA",
    responsibilities: [
      "Design wireframes and prototypes using Figma.",
      "Conduct user research and usability testing.",
      "Collaborate with product and engineering teams.",
    ],
    skills: [
      "Figma",
      "Adobe XD",
      "User Research",
      "Prototyping",
      "Design Thinking",
    ],
    qualifications: [
      "B.Des or equivalent",
      "1–3 years of experience in UI/UX design",
    ],
    perks: ["Design conferences", "Flexible work hours", "Wellness programs"],
  },
  {
    id: 5,
    title: "DevOps Engineer",
    location: "Chennai",
    company: "Flipkart",
    logo: "https://logo.clearbit.com/flipkart.com",
    type: "Full Time",
    salary: "₹10,00,000 – ₹14,00,000 LPA",
    responsibilities: [
      "Automate CI/CD pipelines and infrastructure deployment.",
      "Manage cloud resources and ensure uptime.",
      "Monitor performance and troubleshoot production issues.",
    ],
    skills: ["AWS", "Docker", "Kubernetes", "Jenkins", "Terraform"],
    qualifications: [
      "B.Tech/B.E. in IT or related field",
      "2+ years experience",
    ],
    perks: ["Free snacks", "Remote option", "Learning budget"],
  },
  {
    id: 6,
    title: "Mobile App Developer",
    location: "Delhi",
    company: "Zomato",
    logo: "https://logo.clearbit.com/zomato.com",
    type: "Full Time",
    salary: "₹8,00,000 – ₹11,00,000 LPA",
    responsibilities: [
      "Develop cross-platform mobile apps using React Native.",
      "Work with APIs and integrate backend services.",
      "Publish apps to Play Store and App Store.",
    ],
    skills: ["React Native", "Firebase", "Redux", "Android", "iOS"],
    qualifications: [
      "B.E. in Computer Science",
      "1–3 years of app development experience",
    ],
    perks: ["Meal coupons", "Health insurance", "Remote work"],
  },
  {
    id: 7,
    title: "Full Stack Developer",
    location: "Pune",
    company: "TCS",
    logo: "https://logo.clearbit.com/tcs.com",
    type: "Full Time",
    salary: "₹6,50,000 – ₹9,50,000 LPA",
    responsibilities: [
      "Build and maintain full-stack applications.",
      "Collaborate on project planning and sprint execution.",
      "Write scalable and testable code.",
    ],
    skills: ["MERN Stack", "GraphQL", "Docker", "CI/CD"],
    qualifications: ["B.Tech in CS/IT", "2–5 years experience"],
    perks: ["Work from home", "Paid holidays", "Training programs"],
  },
  {
    id: 8,
    title: "Data Analyst",
    location: "Noida",
    company: "Paytm",
    logo: "https://logo.clearbit.com/paytm.com",
    type: "Full Time",
    salary: "₹5,50,000 – ₹8,00,000 LPA",
    responsibilities: [
      "Analyze business data and generate insights.",
      "Prepare dashboards and reports for stakeholders.",
      "Work with SQL and BI tools.",
    ],
    skills: ["SQL", "Excel", "Power BI", "Python", "Data Visualization"],
    qualifications: ["B.Sc. in Statistics/Maths", "1–3 years experience"],
    perks: ["Work laptop", "Flexible shifts", "Quarterly incentives"],
  },
  {
    id: 9,
    title: "QA Engineer",
    location: "Kolkata",
    company: "Infosys",
    logo: "https://logo.clearbit.com/infosys.com",
    type: "Full Time",
    salary: "₹4,50,000 – ₹7,00,000 LPA",
    responsibilities: [
      "Test web/mobile applications manually and via automation.",
      "Write test cases and report bugs.",
      "Ensure software meets quality standards.",
    ],
    skills: ["Manual Testing", "Selenium", "JIRA", "API Testing", "TestNG"],
    qualifications: ["B.Tech or BCA", "0–2 years experience"],
    perks: ["Certification reimbursement", "Health insurance", "Team outings"],
  },
  {
    id: 10,
    title: "Cybersecurity Analyst",
    location: "Ahmedabad",
    company: "Cisco",
    logo: "https://logo.clearbit.com/cisco.com",
    type: "Full Time",
    salary: "₹9,00,000 – ₹13,00,000 LPA",
    responsibilities: [
      "Monitor network traffic for suspicious activity.",
      "Implement security measures and audits.",
      "Respond to cybersecurity incidents and breaches.",
    ],
    skills: ["Network Security", "Firewalls", "SIEM", "Linux", "Python"],
    qualifications: [
      "B.E./B.Tech in IT/Security",
      "2+ years of security experience",
    ],
    perks: ["Conference sponsorship", "On-call bonuses", "Remote friendly"],
  },
];

export {
  companies_list,
  industries,
  jobData,
  profile_data,
  links,
  comapany_Info_jobData,
  jobLocations,
  reviews,
  CompanyJobsData,
};
